version: '3.9'

networks:
  mynetwork:
    external:
      name: $DOCKER_NETWORK

services:
  cloudflare:
    image: erisamoe/cloudflared
    container_name: cloudflare
    restart: unless-stopped
    command: tunnel run --protocol=http2
    ports:
      - 7844:7844/udp
    environment:
      - TUNNEL_TOKEN=$CLOUDFLARE_TUNNEL_TOKEN
    networks:
      - mynetwork
  timemachine:
    image: odarriba/timemachine
    container_name: timemachine
    restart: unless-stopped
    volumes:
      - $TIMEMACHINE_ROOT:/timemachine
    ports:
      - 548:548
      - 636:636
    environment:
      - AFP_SIZE_LIMIT=250000
      - AFP_NAME=Backups
  uptimekuma:
    image: louislam/uptime-kuma:latest
    container_name: uptimekuma
    ports:
      - "3001:3001"
    volumes:
      - $CONFIG_ROOT/uptimekuma:/app/data
    restart:
      unless-stopped
    networks:
      - mynetwork
  nevergiveup:
    image: docker
    container_name: nevergiveup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: sh -c "while true; do sleep 60; wget -q --spider $CLOUDFLARE_DOMAIN || docker-compose restart cloudflare; done"
    depends_on:
      - cloudflare
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - $CONFIG_ROOT/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - mynetwork
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
