version: '3.9'

networks:
  mynetwork:
    external:
      name: $DOCKER_NETWORK

services:
  cloudflare:
    container_name: cloudflare
    image: erisamoe/cloudflared
    restart: unless-stopped
    command: tunnel run
    ports:
      - 7844:7844/udp
    environment:
      - TUNNEL_TOKEN=$CLOUDFLARE_TUNNEL_TOKEN
    networks:
      - mynetwork

  timemachine:
    container_name: timemachine
    image: odarriba/timemachine
    restart: unless-stopped
    volumes:
      - $TIMEMACHINE_ROOT:/timemachine
    ports:
      - 548:548
      - 636:636
    environment:
      - AFP_SIZE_LIMIT=250000
      - AFP_NAME=Backups

  uptimekuma:
    container_name: uptimekuma
    image: louislam/uptime-kuma:latest
    ports:
      - "3001:3001"
    volumes:
      - $CONFIG_ROOT/uptimekuma:/app/data
    restart:
      unless-stopped
    networks:
      - mynetwork

  portainer:
    container_name: portainer
    image: portainer/portainer
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - $CONFIG_ROOT/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - mynetwork

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - $CONFIG_ROOT/grafana:/var/lib/grafana
    depends_on:
      - influxdb
    networks:
      - mynetwork

  influxdb:
    container_name: influxdb
    image: influxdb:1.8-alpine
    restart: unless-stopped
    volumes:
      - $CONFIG_ROOT/influxdb:/var/lib/influxdb
      - $STORAGE_ROOT/data/influxdb/data:/var/lib/influxdb/data
      - $STORAGE_ROOT/data/influxdb/wal:/var/lib/influxdb/wal
    environment:
      - INFLUXDB_ADMIN_USER=$INFLUXDB_ADMIN_USER
      - INFLUXDB_ADMIN_PASSWORD=$INFLUXDB_ADMIN_PASSWORD
      - INFLUXDB_DB=influx
    networks:
      - mynetwork

  speedtest:
    container_name: speedtest
    image: quadstingray/speedtest-influxdb:0.8.0
    restart: unless-stopped
    environment:
      - INTERVAL=300
      - INCLUDE_READABLE_OUTPUT=true
      - INFLUXDB_DB=influx
      - INFLUXDB_USER=$INFLUXDB_ADMIN_USER
      - INFLUXDB_PWD=$INFLUXDB_ADMIN_PASSWORD
    networks:
      - mynetwork
    depends_on:
      - influxdb

  telegraf:
    container_name: telegraf
    image: telegraf
    restart: unless-stopped
    volumes:
      - $CONFIG_ROOT/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro # this file needs to be created manually
      - $STORAGE_ROOT:/Storage # for stats
      - $TIMEMACHINE_ROOT:/Time-Machine # for stats
      - /proc:/host/proc:ro
      - /var/run/utmp:/var/run/utmp:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - HOST_PROC=/host/proc
      - HOST_PROC_MOUNTINFO=/proc/1
    depends_on:
      - influxdb
    networks:
      - mynetwork
    ports:
      - '8125:8125'

  homer:
    container_name: homer
    image: b4bz/homer:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - mynetwork
    volumes:
      - $CONFIG_ROOT/homer:/www/assets:rw
    user: 0:0 # to get around permissions issues on the volume

  photoprism:
    container_name: photoprism
    image: photoprism/photoprism:preview # or :latest
    restart: unless-stopped
    stop_grace_period: 10s
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - "2342:2342"
    networks:
      - mynetwork
    # see all options here https://dl.photoprism.app/docker/docker-compose.yml
    environment:
      - PHOTOPRISM_ADMIN_USER=$PHOTOPRISM_ADMIN_USER  # admin login username
      - PHOTOPRISM_ADMIN_PASSWORD=$PHOTOPRISM_ADMIN_PASSWORD # initial admin password (8-72 characters)
      - PHOTOPRISM_AUTH_MODE="password"               # authentication mode (public, password)
      - PHOTOPRISM_SITE_URL="https://photos.$CLOUDFLARE_DOMAIN"  # server URL in the format "http(s)://domain.name(:port)/(path)"
      - PHOTOPRISM_ORIGINALS_LIMIT=200000000          # file size limit for originals in MB (increase for high-res video)
      - PHOTOPRISM_HTTP_COMPRESSION="gzip"            # improves transfer speed and bandwidth utilization (none or gzip)
      - PHOTOPRISM_LOG_LEVEL="info"                   # log level: trace, debug, info, warning, error, fatal, or panic
      - PHOTOPRISM_READONLY=false                     # do not modify originals directory (reduced functionality)
      - PHOTOPRISM_EXPERIMENTAL=true                  # enables experimental features
      - PHOTOPRISM_JPEG_QUALITY=85                    # a higher value increases the quality and file size of JPEG images and thumbnails (25-100)
      - PHOTOPRISM_DETECT_NSFW=true                   # automatically flags photos as private that MAY be offensive (requires TensorFlow)
      - PHOTOPRISM_UPLOAD_NSFW=true                   # allows uploads that MAY be offensive (no effect without TensorFlow)
      - PHOTOPRISM_DATABASE_DRIVER="mysql"            # use MariaDB 10.5+ or MySQL 8+ instead of SQLite for improved performance
      - PHOTOPRISM_DATABASE_SERVER="mariadb:3306"     # MariaDB or MySQL database server (hostname:port)
      - PHOTOPRISM_DATABASE_NAME="photoprism"         # MariaDB or MySQL database schema name
      - PHOTOPRISM_DATABASE_USER=$MARIADB_USER        # MariaDB or MySQL database user name
      - PHOTOPRISM_DATABASE_PASSWORD=$MARIADB_PASSWORD # MariaDB or MySQL database user password
      - PHOTOPRISM_SITE_CAPTION="AI-Powered Photos App"
      - PHOTOPRISM_INIT="https gpu tensorflow"
      - PHOTOPRISM_FFMPEG_ENCODER="intel"             # FFmpeg encoder ("software", "intel", "nvidia", "apple", "raspberry")
      - PHOTOPRISM_UID=1000
      - PHOTOPRISM_GID=1000
    user: "1000:1000"
    working_dir: "/photoprism"
    ## Share hardware devices with FFmpeg and TensorFlow (optional):
    devices:
     - "/dev/dri:/dev/dri"                         # Intel QSV
    volumes:
      - $STORAGE_ROOT/photoprism/originals:/photoprism/originals
      - $STORAGE_ROOT/photoprism/storage:/photoprism/storage

  mariadb:
    container_name: mariadb
    image: mariadb:10.11
    restart: unless-stopped
    stop_grace_period: 5s
    networks:
      - mynetwork
    security_opt: # see https://github.com/MariaDB/mariadb-docker/issues/434#issuecomment-1136151239
      - seccomp:unconfined
      - apparmor:unconfined
    command: mariadbd --innodb-buffer-pool-size=512M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    volumes:
      - $CONFIG_ROOT/mariadb/mysql:/var/lib/mysql" # DO NOT REMOVE
    environment:
      - MARIADB_AUTO_UPGRADE="1"
      - MARIADB_INITDB_SKIP_TZINFO="1"
      - MARIADB_DATABASE="photoprism"
      - MARIADB_USER=$MARIADB_USER
      - MARIADB_PASSWORD=$MARIADB_PASSWORD
      - MARIADB_ROOT_PASSWORD=$MARIADB_PASSWORD

  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant
    restart: always
    volumes:
      - $CONFIG_ROOT/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    network_mode: "host"

  hacs:
    container_name: hacs
    image: frolvlad/alpine-bash:latest
    restart: "no"
    volumes:
      - $CONFIG_ROOT/homeassistant:/config
    entrypoint: sh -c "apk add --no-cache wget && wget -O - https://get.hacs.xyz | bash -"
